config/routes.rb
Warsztaty::Application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :posts

  

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  validates :content, :presence => :true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  validates :email, :presence => :true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render action: "new"
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully created."
    else
      render action: "edit"
    end
  end

  def destroy
    @post.destroy
    redirect_to @posts
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Warsztaty SCRUM</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="jumbotron">
  <h1 id="h1"> <a href="/"> Welcome to Coders Lab</a></h1>
  <% if user_signed_in? -%>

      <p>Jesteś zalogowany jako <%= current_user.email -%></p>


      <div class="btn-toolbar" role="toolbar">
        <%= link_to "Posts Index",  posts_path ,class:"btn btn-default btn-lg" -%>

        <div class="btn-group pull-right" >
        <%= link_to "Edit Account",  edit_user_registration_path ,class:"btn btn-primary btn-lg" -%>
        <%= link_to "Sign Out",     destroy_user_session_path ,class:"btn btn-primary btn-lg", method: :delete -%>
     </div>
       </div>




  <% else -%>
      <p>Nie jesteś zalogowany</p>

      <div class="btn-group" id="buttons">
        <%= link_to "Login",  new_user_session_path ,class:"btn btn-primary btn-lg" -%>

        <%= link_to "Sign Up",  new_user_registration_path ,class:"btn btn-primary btn-lg" -%>
      </div>

  <% end -%>
</div>

<%= yield %>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "well col-md-4 col-md-offset-4"} do |f| %>
    <div class="form-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="form-group">
        <%= f.text_area :content, :class => 'form-control' %>
      </div>
      <div class="form-actions">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    posts_path, :class => 'btn' %>
      </div>
<% end %>

app/views/posts/edit.html.erb
<%= form_for @post, :html => { :class => "well col-md-4 col-md-offset-4"} do |f| %>
    <div class="form-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="form-group">
        <%= f.text_area :content, :class => 'form-control' %>
      </div>
      <div class="form-actions">
        <%= f.submit nil, :class => 'btn btn-primary' %>


<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            post_path(@post),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are
you sure?')) },
            :class => 'btn btn-danger' %>

        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    posts_path, :class => 'pull-right btn' %>

      </div>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
        <div class="well col-md-4 col-md-offset-4">
        <% unless post.user.name.blank? %>
            <%= post.user.name %>
        <% else %>
            <%= post.user.email %>
        <% end %>
        wrote:
        </br>
        <%= image_tag "post.user.avatar", class: "img-circle", id: "avatar" %>
        <%= post.content %>
        <% if current_user == post.user -%>

            <%= link_to "Edit",  edit_post_path(post), class:"pull-right btn btn-success" -%>
        <% end %>
        </div>
<% end %>

app/views/posts/new.html.erb
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<div class="well col-md-4 col-md-offset-4">
  <div>
    <% unless @post.user.name.blank? %>
        <%= @post.user.name %>
    <% else %>
        <%= @post.user.email %>
    <% end %>
     wrote:
  </div>
  </br>

  <img url="..." class="img-circle" id="avatar">
  <%= @post.content %>
  <% if current_user == @post.user -%>

      <%= link_to "Edit",  edit_post_path(@post), class:"pull-right btn btn-success" -%>
  <% end %>
</div>